### ISSUE TITLE
Missing header-files

### ISSUE THREAD

**Issue by RuneEspeseth** [PLCnext/BusConductor#1]
In BcComponent.hpp:

**#include "BcComponentProgramProvider.hpp"
#include "BusConductorLibrary.hpp"**

but these files are not present in the repo.

**Comment by OWarneke** [comment]
These files are autogenerated during the building process by the "PLCnCLI".

see the README chapter Building from source.
plcncli generate code -> Here the providers ect. are generated
plcncli generate config
plcncli build
plcncli generate library
