### ISSUE TITLE
C++ Build error "string not declared"

### ISSUE THREAD

**Issue by declan-pxc** [PLCnext/BusConductor#6]
Trying to do an initial build of the project (build target -n 2152 -v 24.0). When building the application I get an error that string is not declared.

```
[cmake]: In file included from C:/Users/.../.../BusConductor/intermediate/code/BcComponent.meta.cpp:1
[cmake]: C:/Users/.../.../BusConductor/src/BcComponent.hpp:78:48: error: 'string' has not been declared   
[cmake]:  78 |   bool ConfigureLocalIo(bool validateConfig, string configFile  
﻿[cmake]:    |                                               ^~~~~
[cmake]: make[2]: *** [CMakeFiles/BusConductor.dir/build.make:76: CMakeFiles/BusConductor.dir/intermediate/code/BcComponent.meta.cpp.o] Error 1
[cmake]: make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/BusConductor.dir/all] Error 2 
﻿[cmake]: make: *** [Makefile:136: all] Error 2                                              cmake process exited with error 
```

Has something fundamentally changed between SDK 2021 and 2024 w.r.t strings?

The repo was downloaded directly and the only change was updating the target.

**Comment by martinboers** [comment]
Hmm, we must have been "lucky" with SDK 2021.6 - I just checked that this SDK still works, but it seems that SDKs after that don't work.

With SDK 2021.6 the following directive must have been included in one of the Arp header files:

```cpp
using namespace std;
```

... which automatically resolves the `string` type (and also some other types) used in the component in this project.

It would be good practice to explicitly add this directive to the source code here, which I will do when I have the chance. In the mean time, simply adding that line in your copy of `BcComponent.hpp` (near the top, with the other `using namespace ...` lines) should allow you to build the project.

**Comment by martinboers** [comment]
Actually, the 2025.0-Preview branch already fixes this issue. The code in that branch should work with all SDKs, up to and including the SDK for the 2025.0 Preview device "SIM-AXCF2152", version 2024.7. We were planning to merge that branch into the master branch when FW 2025.0 is released (in the first half of next year), but that branch should work now.
